# Generated by Django 3.2 on 2021-05-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
